## Write a Numpy program to compute the multiplication of two given matrixes

In [6]:
import numpy as np
mat1=([1,2,3],[4,5,6],[4,8,9])
mat2=([1,2,3],[4,5,6],[7,5,6])
result=np.dot(mat1,mat2)
print(result)

[[ 30  27  33]
 [ 66  63  78]
 [ 99  93 114]]


## Write a NumPy program to compute the determinant of a given square array

In [1]:
import numpy as np
mat1=([1,2,3],[4,5,6],[4,8,9])
result=np.linalg.det(mat1)
print(result)

9.000000000000002


In [2]:
import numpy as np
mat2=([1,2,3],[4,5,6],[7,5,6])
result=np.linalg.det(mat2)
print(result)

-8.999999999999998


## Write a NumPy program to compute the cross product of two given vectors

In [4]:
import numpy as np
x = [[1, 2],[3,4]]
y = [[5, 6],[7,8]]
result = np.cross(x, y)
print(result)

[-4 -4]


## Write a NumPy program to compute the condition number of a given matrix

In [5]:
import numpy as np
mat1=([1,2,3],[4,5,6],[4,8,9])
result=np.linalg.cond(mat1)
print(result)

32.189556718851804


## Write a NumPy program to compute the inverse of a given matrix

In [7]:
import numpy as np
mat1=([1,2,3],[4,5,6],[4,8,9])
result=np.linalg.inv(mat1)
print(result)

[[-0.33333333  0.66666667 -0.33333333]
 [-1.33333333 -0.33333333  0.66666667]
 [ 1.33333333  0.         -0.33333333]]
